# Generated by Django 5.2.17 on 2026-09-16 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student (max 100 characters)', max_length=100)),
                ('register_number', models.CharField(help_text='Unique register/roll number (max 20 characters)', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Unique email address', max_length=254, unique=True)),
                ('department', models.CharField(help_text='Department name (max 100 characters, e.g. CSE, ECE, MECH)', max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text='Current year of study (1, 2, 3, or 4)', validators=[django.core.validators.MinValueValidator(1, message='Year must be at least 1.'), django.core.validators.MaxValueValidator(4, message='Year must be at most 4.')])),
                ('phone', models.CharField(help_text='10-digit Indian mobile number', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit Indian mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the student record was created')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
