# Generated by Django 5.2.17 on 2026-09-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_collegesettings_options_and_more'),
        ('students', '0003_nullable_legacy_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department assigned to the student', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='college.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=30, null=True),
        ),
    ]
