# Generated by Django 5.2.17 on 2026-09-16 18:04

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_records(apps, schema_editor):
    CollegeSettings = apps.get_model('college', 'CollegeSettings')
    college = CollegeSettings.objects.order_by('id').first()
    if not college:
        return
    apps.get_model('college', 'Department').objects.filter(college__isnull=True).update(college_id=college.id)
    apps.get_model('college', 'UserAccess').objects.filter(college__isnull=True).update(college_id=college.id)
    apps.get_model('students', 'Student').objects.filter(college__isnull=True).update(college_id=college.id)


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_department_college_useraccess_college'),
        ('students', '0005_student_admission_year_student_backlog_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='college.collegesettings'),
        ),
        migrations.RunPython(assign_existing_records, migrations.RunPython.noop),
    ]
