# Generated by Django 5.2.17 on 2026-09-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegesettings',
            options={'verbose_name': 'College Settings', 'verbose_name_plural': 'College Settings'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
