# Generated by Django 5.2.17 on 2026-09-16 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_collegesettings_admin_user_department_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('can_view_students', models.BooleanField(default=True)),
                ('can_add_students', models.BooleanField(default=False)),
                ('can_edit_students', models.BooleanField(default=False)),
                ('can_delete_students', models.BooleanField(default=False)),
                ('can_manage_departments', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
