# Generated by Django 5.2.17 on 2026-09-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='college.collegesettings'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='college.collegesettings'),
        ),
    ]
