import React, { useEffect, useState } from 'react';
import { accessApi, settingsApi } from '../services/api';

const Settings = ({ showToast, collegeName }) => {
  const [form, setForm] = useState({ college_name: collegeName || '', admin_email: '' });
  const [saving, setSaving] = useState(false); const [users, setUsers] = useState([]); const [newUser, setNewUser] = useState({ email: '', password: '' });
  useEffect(() => { settingsApi.get().then((result) => result.data && setForm({ college_name: result.data.college_name || '', admin_email: result.data.admin_email || '' })).catch((error) => showToast(error.message, 'error')); accessApi.getAll().then(setUsers).catch(() => {}); }, [showToast]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await settingsApi.update(form.college_name, form.admin_email); showToast('Institution settings updated.', 'success'); } catch (error) { showToast(error.message, 'error'); } finally { setSaving(false); } };
  const createUser = async (event) => { event.preventDefault(); try { const user = await accessApi.create(newUser.email, newUser.password); setUsers([...users, user]); setNewUser({ email: '', password: '' }); showToast('User created.', 'success'); } catch (error) { showToast(error.message, 'error'); } };
  const updatePermission = async (user, field) => { try { const updated = await accessApi.update(user.id, { [field]: !user[field] }); setUsers(users.map((item) => item.id === updated.id ? updated : item)); } catch (error) { showToast(error.message, 'error'); } };
  return <div className="settings-page"><section className="card settings-card"><h1 className="page-title">College Settings</h1><p className="page-subtitle">Manage your institution profile and authorized administrator email.</p><form onSubmit={submit} className="auth-form"><label className="form-label">College Name<input className="form-input" value={form.college_name} onChange={(event) => setForm({ ...form, college_name: event.target.value })} required /></label><label className="form-label">Authorized Admin Email<input className="form-input" type="email" value={form.admin_email} onChange={(event) => setForm({ ...form, admin_email: event.target.value })} required /></label><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving...' : 'Save Settings'}</button></form><hr /><h2>User Permissions</h2><p className="page-subtitle">Create users and control what they can change.</p><form onSubmit={createUser} className="department-form-row"><input className="form-input" type="email" placeholder="User email" value={newUser.email} onChange={(event) => setNewUser({ ...newUser, email: event.target.value })} required /><input className="form-input" type="password" placeholder="Temporary password" value={newUser.password} onChange={(event) => setNewUser({ ...newUser, password: event.target.value })} required /><button className="btn btn-primary">Add User</button></form><div className="permission-list">{users.map((user) => <div className="permission-row" key={user.id}><strong>{user.username}</strong>{['can_view_students', 'can_add_students', 'can_edit_students', 'can_delete_students', 'can_manage_departments'].map((field) => <label key={field}><input type="checkbox" checked={Boolean(user[field])} onChange={() => updatePermission(user, field)} />{field.replace('can_', '').replaceAll('_', ' ')}</label>)}</div>)}</div></section></div>;
};

export default Settings;