import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Save, ArrowLeft } from 'lucide-react';
import { studentApi } from '../services/api';

const EMPTY = { name: '', register_number: '', email: '', gender: '', department: '', year: '', phone: '', admission_year: '', cutoff_mark: '', previous_semester_percentage: '', cgpa: '', backlog_count: '0', status: 'active' };

const StudentEditor = ({ departments, departmentsLoading, departmentsError, onRefreshDepartments, onSave, showToast }) => {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id); const [form, setForm] = useState(EMPTY); const [errors, setErrors] = useState({}); const [loading, setLoading] = useState(editing);
  useEffect(() => { if (editing) studentApi.getStudent(id).then((student) => setForm({ ...EMPTY, ...student, department: student.department ? String(student.department) : '' })).catch((error) => showToast(error.message, 'error')).finally(() => setLoading(false)); }, [id, editing, showToast]);
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const validate = () => { const next = {}; ['name', 'register_number', 'email', 'gender', 'department', 'year', 'phone'].forEach((key) => { if (!String(form[key]).trim()) next[key] = 'This field is required.'; }); if (form.email && !/^\S+@\S+\.\S+$/.test(form.email)) next.email = 'Enter a valid email address.'; if (form.phone && !/^[6-9]\d{9}$/.test(form.phone)) next.phone = 'Enter a valid 10-digit Indian mobile number.'; if (form.previous_semester_percentage !== '' && (form.previous_semester_percentage < 0 || form.previous_semester_percentage > 100)) next.previous_semester_percentage = 'Must be between 0 and 100.'; if (form.cgpa !== '' && (form.cgpa < 0 || form.cgpa > 10)) next.cgpa = 'Must be between 0 and 10.'; if (form.backlog_count !== '' && (!/^\d+$/.test(String(form.backlog_count)) || Number(form.backlog_count) < 0)) next.backlog_count = 'Use a non-negative whole number.'; setErrors(next); return !Object.keys(next).length; };
  const submit = async (event) => { event.preventDefault(); if (!validate()) return; const payload = { ...form, department: Number(form.department), year: Number(form.year), admission_year: form.admission_year === '' ? null : Number(form.admission_year), cutoff_mark: form.cutoff_mark === '' ? null : Number(form.cutoff_mark), previous_semester_percentage: form.previous_semester_percentage === '' ? null : Number(form.previous_semester_percentage), cgpa: form.cgpa === '' ? null : Number(form.cgpa), backlog_count: Number(form.backlog_count || 0) }; const ok = await onSave(id, payload); if (ok) navigate('/students'); };
  const control = (name, label, type = 'text', options = null) => <div className="form-group"><label className="form-label" htmlFor={`student-${name}`}>{label}{!['admission_year', 'cutoff_mark', 'previous_semester_percentage', 'cgpa', 'backlog_count'].includes(name) && <span className="required-star"> *</span>}</label>{options ? <select id={`student-${name}`} name={name} className="form-select" value={form[name]} onChange={update}><option value="">{label === 'Department' ? 'Select Department' : `Select ${label}`}</option>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select> : <input id={`student-${name}`} name={name} type={type} className="form-input" value={form[name] ?? ''} onChange={update} min={name === 'backlog_count' ? 0 : undefined} />}{errors[name] && <span className="field-error-msg">{errors[name]}</span>}</div>;
  if (loading) return <div className="state-container loading-state"><div className="spinner" /></div>;
  const departmentControl = departmentsLoading ? <div className="field-status">Loading departments...</div> : departmentsError ? <div className="field-status field-error-msg">{departmentsError} <button type="button" className="btn btn-secondary btn-small" onClick={onRefreshDepartments}>Retry</button></div> : departments.length === 0 ? <div className="field-status">No departments have been added yet. <Link to="/departments">Add Department</Link></div> : null;
  return <div className="student-editor-page"><Link to="/students" className="back-link"><ArrowLeft size={16} /> Back to Students</Link><section className="card student-editor-card"><div className="page-header"><div><h1 className="page-title">{editing ? 'Edit Student' : 'Add New Student'}</h1><p className="page-subtitle">Manage the complete student record.</p></div></div><form onSubmit={submit}><h2 className="form-section-title">Student Information</h2><div className="form-grid editor-grid">{control('name', 'Full Name')}{control('register_number', 'Register Number')}{control('email', 'Email', 'email')}{control('gender', 'Gender', 'text', [['male', 'Male'], ['female', 'Female']])}{departmentControl || control('department', 'Department', 'text', departments.map((department) => [department.id, department.name]))}{control('year', 'Year of Study', 'text', [[1, '1st Year'], [2, '2nd Year'], [3, '3rd Year'], [4, '4th Year']])}{control('phone', 'Mobile Phone', 'tel')}{control('admission_year', 'Admission Year', 'number')}</div><h2 className="form-section-title">Academic Information</h2><div className="form-grid editor-grid">{control('cutoff_mark', 'Cutoff Mark', 'number')}{control('previous_semester_percentage', 'Previous Semester Percentage', 'number')}{control('cgpa', 'CGPA', 'number')}{control('backlog_count', 'Backlog Count', 'number')}{control('status', 'Student Status', 'text', [['active', 'Active'], ['graduated', 'Graduated'], ['left_college', 'Left College']])}</div><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={() => navigate('/students')}>Cancel</button><button type="submit" className="btn btn-primary"><Save size={16} /> {editing ? 'Save Changes' : 'Add Student'}</button></div></form></section></div>;
};

export default StudentEditor;